mailconfig:
  email: your.mail@sample.com
  email_from: Your Name
  imap_server: imap.sample.com
  imap_port: 993
  email_text: here the bill as usual.

bill_config:
  header: Bill für Stuff
  company: Sample Inc.
  name: Your Name
  street: Your street
  city: Your city
  country: DE
  postcode: "12345"
  telephone: "+49 123 4567890"
  telephone_concise: "++491234567890"
  email: your.mail@sample.com
  company_web: sample.com
  vat_id: DE12345678
  tax_id: 12/345/67890
  color: "#99d0ba"
  text: anbei meine Rechnung bezüglich bla bla bla.

bank_config:
  bank_name: Your Bank
  bic: BLABLA1000
  iban: "DE12 3456 7890 1234 5678 90"
  name: Your name

companies:

  CustomerCompany:
    email: mail@customer-company.com
    subject: Bill for stuff done for customer company
    greeting_to: Hi everyone,
    greeting_from: "Kind regards\nYour name\n\n"
    hourly_fee: 100
    address:
      name: "Customer Company Inc."
      city: Customer city
      postcode: "12345"
      addressline: Customer street